<?php
$form->setAttribute('action', $this->url('application', ['action' => 'index']));
$form->prepare();
?>

<div class="container">
    <div class="wrapper fadeInDown">
        <div id="formContent">
            <!-- Tabs Titles -->

            <!-- Icon -->
            <div class="fadeIn first">
                <figure>
                    <img src="<?= $this->basePath('img/login.png') ?>" id="icon" alt="User Icon" class="w-25" />
                </figure>
            </div>

            <!-- Login Form -->
            <form class="p-3" action="<?php echo $form->getAttribute('action'); ?>"
                  method="<?php echo $form->getAttribute('method'); ?>">
                <div class="form-group">
                    <?php echo $this->formElement($form->get('username')); ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formElement($form->get('password')); ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formButton($form->get('submit'), 'Login'); ?>
                </div>
            </form>
        </div>
    </div>
</div>
